source 'https://rubygems.org'

ruby '2.2.8'

gem 'rails',                     '4.2.0'

gem 'dotenv-rails',              '~> 2.2.1'

gem 'airbrake',                  '~> 4.2.1'
gem 'bootstrap-sass',            '~> 3.3.7'
gem 'coffee-rails',              '~> 4.2.2'
gem 'font-awesome-rails',        '~> 4.7.0'
gem 'high_voltage',              '~> 2.2.1'
gem 'jbuilder',                  '~> 2.2.16'
gem 'jquery-rails',              '~> 4.0.5'
gem 'libv8',                     '~> 3.16.14.19'
gem 'omniauth',                  '~> 1.2.2'
gem 'omniauth-browserid',        '~> 0.0.1'
gem 'omniauth-facebook',         '~> 2.0.1'
gem 'omniauth-gitlab',           '~> 1.0.2'
gem 'omniauth-google-oauth2',    '~> 0.2.10'
gem 'omniauth-openid',           '~> 1.0.1'
gem 'omniauth-shibboleth',       '~> 1.2.1'
gem 'omniauth-twitter',          '~> 1.2.1'
gem 'paranoia',                  '~> 2.1.5'
gem 'pg',                        '~> 0.18.4'
gem 'rack-cache',                '~> 1.7.1'
gem 'rails_serve_static_assets', '~> 0.0.5'
gem 'rails_stdout_logging',      '~> 0.0.5'
gem 'rb-readline',               '~> 0.5.5'
gem 'redis',                     '~> 3.2.2'
gem 'redis-namespace',           '~> 1.5.3'
gem 'redis-rack-cache',          '~> 1.2.4'
gem 'redis-rails',               '~> 4.0.0'
gem 'responders',                '~> 2.1.2'
gem 'ruby-saml',                 '~> 0.9.2'
gem 'sass-rails',                '~> 5.0.7'
gem 'therubyracer',              '~> 0.12.3'
gem 'turbolinks',                '~> 2.5.3'
gem 'uglifier',                  '~> 2.7.2'
gem 'unicorn',                   '~> 4.9.0'

group :development, :test do
  gem 'byebug',                  '~> 3.5.1'
  gem 'rails_layout',            '~> 1.0.24'
  gem 'spring',                  '~> 1.3.6'
  gem 'web-console',             '~> 2.0'
end
