source 'https://rubygems.org'

ruby '2.7.0'

gem 'rails',                     '5.2.4.1'

gem 'dotenv-rails',              '~> 2.2.1'

gem 'bootstrap-sass',            '~> 3.4.1'
gem 'coffee-rails',              '~> 4.2.2'
gem 'font-awesome-rails',        '~> 4.7.0'
gem 'high_voltage',              '~> 3.0.0'
gem 'jbuilder',                  '~> 2.7.0'
gem 'jquery-rails',              '~> 4.3.1'
gem 'libv8',                     '~> 3.16.14.19'
gem 'omniauth',                  '~> 1.7.1'
gem 'omniauth-browserid',        '~> 0.0.1'
gem 'omniauth-facebook',         '~> 4.0.0'
gem 'omniauth-gitlab',           '~> 1.0.2'
gem 'omniauth-openid',           '~> 1.0.1'
gem 'omniauth-shibboleth',       '~> 1.3.0'
gem 'omniauth-twitter',          '~> 1.4.0'
gem 'paranoia',                  '~> 2.4.0'
gem 'pg',                        '~> 0.21.0'
gem 'rack-cache',                '~> 1.7.1'
gem 'rails_serve_static_assets', '~> 0.0.5'
gem 'rails_stdout_logging',      '~> 0.0.5'
gem 'rb-readline',               '~> 0.5.5'
gem 'responders',                '~> 2.4.0'
gem 'ruby-saml',                 '~> 1.7.0'
gem 'sass-rails',                '~> 5.0.7'
gem 'therubyracer',              '~> 0.12.3'
gem 'turbolinks',                '~> 5.0.1'
gem 'uglifier',                  '~> 4.0.1'
gem 'unicorn',                   '~> 5.3.1'

group :development, :test do
  gem 'byebug',                  '~> 11.0.1'
  gem 'listen',                  '~> 3.1.5'
  gem 'rails_layout',            '~> 1.0.24'
  gem 'spring',                  '~> 2.0.2'
  gem 'web-console',             '~> 3.5.1'
end
